### ISSUE TITLE
Petty/Weightless Armor

### ISSUE THREAD

**Issue by Yochien** [yochaigal/Cairn-FoundryVTT#109]
Allow for the creation of weightless armor.

As an example, a player receives "an iron helm (+1 Armor, petty)" on pg. 132 of the Cairn 2e Warden's Guide.

Modifying `templates/item/armor-sheet.html` to include the weightless section from `templates/item/item-sheet.html` ~~worked fine for my purposes~~ provides the expected functionality but places the cost parameter awkwardly below the item description.

**Comment by Yochien** [comment]
Combining the weightless property with the number of charges property creates a behavioral collision. The number of charges is not displayed and the -/+ affect the weightless property. This behavior is the same for weapons and armor.

This behavior does not occur if the item is bulky instead of weightless, i.e. weapons and armor can be bulky and have charges.

**Comment by oswida** [comment]
This is intended behaviour. Weightless items do not have "uses", but can have "quantity" as they are not increasing weight, we can put many of them in the same slot.
It is behaviour which was defined in the original version of the system, before I have started development. If you think that some other scenarios would be usable, I'm open for suggestions, however that means we need to refactor the whole "quantity-uses-bulky-weightless" concept.

**Comment by Yochien** [comment]
Understood. My main interest was in having the ability to make weightless weapons and armor which you already implemented in your earlier PR. Thank you :^)

Sticking to the implementation that already exists would it be fair to reset total uses to 0 when an item is marked weightless, similar to when you mark an item bulky it loses the weightless property?

This would make the intended current implementation pretty clear, and anyone could raise a separate issue on the topic of reworking the "quantity-uses-bulky-weightless" concept in the future if needed.
