### ISSUE TITLE
Does this system work with Cairn Second Edition?

### ISSUE THREAD

**Issue by Caius1987** [yochaigal/Cairn-FoundryVTT#114]
Sorry, don't know where else I can ask.

Thank you

**Comment by oswida** [comment]
I would say, yes. 
2ed is identical in terms of mechanics. There are no 2ed content like backgrounds in this version (and I suppose it it will ever be, I would move it to the separate module).
There are some smaller features like "panic", but I am implementing them successively.

**Comment by Caius1987** [comment]
Thank you for the promptly reply. =]
