### ISSUE TITLE
Feature Request: Targeting

### ISSUE THREAD

**Issue by SageDaMage** [yochaigal/Cairn-FoundryVTT#12]
In the Basic Controls, you can select target tokens, so it'd be great if there was a way to automatically check for targets and apply the damage result minus the armor, instead of having to do it manually. Possibly as an option, it could roll STR after lowering it? It'd be nice to be able to apply damage to characters easily without going into their sheets manually.

**Comment by lecrapal** [comment]
Fixed in #80

**Comment by oswida** [comment]
Closing as it is done.
