### ISSUE TITLE
Bug: Character creator generates rations that are already used

### ISSUE THREAD

**Issue by segeeslice** [yochaigal/Cairn-FoundryVTT#121]
## Assumption

When an item has multiple uses, a filled dot means the item was used, and "adding" a use occurs when using it once. This is corroborated by the fact that an item is crossed out when all dots are filled.

*Side note: I bring this assumption up as I'm new to the extension, and the phrasing is a bit confusing to me. I think "# of uses" could be rephrased to "times used" to better emphasize its intent. But this is not the reason for the ticket...*

### Steps Taken

1. Open "Actors" tab
1. Click the "Create character" button: 
![image](https://github.com/user-attachments/assets/a82dec0d-6569-486f-942a-6b6b659099f7)

### Expected Behavior

The created character will have rations in their inventory with 3 charges that are not yet used.

### Actual Behavior

The character is created, but with their rations already used up!

![image](https://github.com/user-attachments/assets/3a1e6dcd-f7f9-4496-a30f-864db3b67a96)

## Build Info

- OS: Pop!_OS Linux 22.04 LTS
- Foundry: Version 12 Stable, Build 331
- Cairn: Version 0.15 *(but also observed on 0.14)*

**Comment by oswida** [comment]
As I haven't changed generator code, I think the basic intent for "uses" was "available uses" or "uses left". This is why created actor has number of uses equal maximum.
I have been changing the item visualization, so probably I have mistaken it at this point.
Thus, I will adjust visualization to the primary intent.
