### ISSUE TITLE
Non-GM Players Get Error on Chat/Roll Actions - getRollData Undefined Check Needed

### ISSUE THREAD

**Issue by MiSiebold** [yochaigal/Cairn-FoundryVTT#123]
## Description
When non-GM players attempt to type in chat or make rolls, the following error appears in the console and no action is posted to chat.

```js
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at CairnActor.getRollData (actor.js:93:31)
    at ChatMessage.getRollData (foundry.js:17635:26)
    at ChatMessage.getHTML (foundry.js:17676:78)
```

The error occurs when any text or roll is manually typed into the Foundry chat box or if any macro with a roll component is triggered. The exception is rolling from the Character Sheets themselves still works - e.g. clicking STR, DEX, WIL. 

* The user permissions within Foundry are set to allow all roles to perform Manual Rolls.
* I have disabled all modules to eliminate the variables
* I have changed player rolls and created new players - if they are not GMs, they cannot roll
* I've restored to previous backups of the game (early Dec) without any fix
* Running Cairn v 0.15 / Foundry VTT V12.331

Could this behavior be occurring if data.abilities on actor.js is undefined during these rolls from not the character sheet?

UPDATE: 
I've had success updating this portion of actor.js. 

/** @override */
getRollData() {
    const data = super.getRollData() || {};
    if (data.abilities) {
        for (const [k, v] of Object.entries(data.abilities)) {
            if (!(k in data)) data[k] = v.value;
        }
    }
    return data;
}

**Comment by oswida** [comment]
This is somehow strange because:
- I was not able to reproduce this error
- This part of code has not changed for 3 years

Nevertheless, I will introduce this change as checking property existence won't break anything.
