### ISSUE TITLE
character sheets don't keep items in inventory

### ISSUE THREAD

**Issue by idolofmanyhands** [yochaigal/Cairn-FoundryVTT#14]
steps to reproduce:
1. run the macro
2. check character sheet
3. log out
4. log in
5. check character sheet (some items are missing)

here an example (in the chat what's have been rolled, on the left the character inventory after re-login)
![image](https://user-images.githubusercontent.com/3481865/115965648-6bc1bb00-a52a-11eb-9012-ed56a1ce7407.png)

**Comment by yochaigal** [comment]
Fixed, thanks @sunflowermans
