### ISSUE TITLE
Attributes aren't displaying in .0.8.6.

### ISSUE THREAD

**Issue by jacob-french** [yochaigal/Cairn-FoundryVTT#31]
Hi, the attributes for STR, DEX and WIL do not appear on the character sheet as they used to.

![image](https://user-images.githubusercontent.com/70240737/120634131-ce2fa480-c462-11eb-8846-d69a74e82a9c.png)

**Comment by yochaigal** [comment]
I am able to reproduce this in the latest version of Foundry (0.8.6).

**Comment by danielbackus** [comment]
This should be fixed by #34
