### ISSUE TITLE
Enhancement: # of Uses

### ISSUE THREAD

**Issue by tuirgin** [yochaigal/Cairn-FoundryVTT#39]
"# OF USES" appears to only be visible and editable within the item's edit sheet which really limits its utility.

1. For rechargeable items it's preferable to have current and max uses; i.e. you've used ItemX 2 out of 3 times. On recharge, you can reset the current uses to 0 without having to remember—or look up—how many charges the fully charged item has.
2. It would be convenient if there were a mechanism to view and manipulate the remaining uses from the ITEMS list. We have this for QUANTITY—quantity is displayed in the ITEMS list, and deleting an item reduces the total quantity.

**Comment by ascendsauce** [comment]
Looking at this. I need some clarification here.

For 1) Do you want this as a manual "recharge" button or would a user just be able to set their uses manually with a +/- button or a text input field? I imagine a recharge button maybe desirable, however it might make the UI a bit busy.

**Comment by yochaigal** [comment]
Hmm a rechage is probably fine - though I don't mind the plus/minus either. Whatever is easier for you.

**Comment by lecrapal** [comment]
Solved by @maqloner
