### ISSUE TITLE
weird character sheet ab display

### ISSUE THREAD

**Issue by dinotheextinct** [yochaigal/Cairn-FoundryVTT#46]
![image](https://user-images.githubusercontent.com/32158581/151657126-1f4085a6-adad-4117-b4c2-29f7c496b009.png)
Are the tabs supposed to look like that?
Also the rolltables seem to have weird distances between each entry:
![image](https://user-images.githubusercontent.com/32158581/151657168-c207b034-65d5-472f-98f3-626ef415c3ce.png)

**Comment by yochaigal** [comment]
Yeah, after the update it got... uglier. I don't know CSS well enough to fix it :).

**Comment by yochaigal** [comment]
Fixed in #47
