### ISSUE TITLE
No tools, no bonus items

### ISSUE THREAD

**Issue by moondog-matthew** [yochaigal/Cairn-FoundryVTT#58]
All my characters generated using the macro are receiving no tools (tools aren't even listed here), and no bonus item either, the roll is always "none" for me. Note that these items do not show up on the character sheet itself either. 

![image](https://user-images.githubusercontent.com/94130507/160150705-31debbca-0ad2-4816-baa9-ca965175cb0e.png)
![image](https://user-images.githubusercontent.com/94130507/160150995-85d531c2-1a2c-4e01-a164-a5ddee8c0f78.png)

**Comment by maqloner** [comment]
This has been solved by the new character generator
