### ISSUE TITLE
Missing icons for "Extras" Compendium

### ISSUE THREAD

**Issue by James-Firth** [yochaigal/Cairn-FoundryVTT#59]
Foundry version 9 Build 255
Cairn 0.10.18

When I looked at my preexisting world in Foundry all the Extras were missing icons
![image](https://user-images.githubusercontent.com/485809/160291954-93e89e1e-3fd5-4366-a3b6-a21b602d0d45.png)

Checking the system folder they seem to be missing now too:
![image](https://user-images.githubusercontent.com/485809/160292007-a90f2ae0-d2de-4b71-ba91-bf71a2bce42a.png)

**Comment by oswida** [comment]
Closing as it seems that all extra icons are in place.
