### ISSUE TITLE
Small issues on 1.10.28

### ISSUE THREAD

**Issue by lecrapal** [yochaigal/Cairn-FoundryVTT#75]
- Weightless items have the +/- icon even if it's not a consumable item
- Weightless tags in item list also show the quantity, like "Weightless 1" if quantity is set to 1
- French translation for Deprived should now be "Épuisé" to follow the srd
- French translation for HP should now be "PC" to follow the srd

**Comment by yochaigal** [comment]
What does "PCto follow the srd" mean here? Is that a typo?

**Comment by lecrapal** [comment]
Yes, i edited it.

**Comment by maqloner** [comment]
The nail was only an example, The goal was only to allow the GMs to have quantity for some type of items, mainly weightless since other items should always take a slot. The alternative was to add the +/- button to all item of type "item" but it was bloating the interface

**Comment by lecrapal** [comment]
I got @maqloner's point on the quantity and the weightless so i'll only work on : 
- Weightless items have the +/- icon even if it's not a consumable item
- French translation for Deprived should now be "Épuisé" to follow the srd
- French translation for HP should now be "PC" to follow the srd
