### ISSUE TITLE
Bonus Item Table is unfinished? Gives me null items

### ISSUE THREAD

**Issue by ScottMaclure** [yochaigal/Cairn-FoundryVTT#8]
Disclaimer: Just getting used to FoundryVTT, still need to learn how to mod etc.

Seems the "Bonus Item" table is incomplete?

I modified my imported table like so:

![image](https://user-images.githubusercontent.com/962320/114257829-14353280-99f5-11eb-83af-b7e6981a05c2.png)

Side note: Spellbooks table also has null items.

**Comment by yochaigal** [comment]
We are working on both of these right now!

**Comment by yochaigal** [comment]
Fixed!
