### ISSUE TITLE
Feature request: Gold value for items

### ISSUE THREAD

**Issue by lars1808** [yochaigal/Cairn-FoundryVTT#81]
With a gold value label for items, selling/buying items through shops such as Monk's Enhanced Journal should be feasible, I hope?
![2022-12-30 18_31_13-Shroud of the Serpent • Foundry Virtual Tabletop](https://user-images.githubusercontent.com/39065518/210097521-eb7f2b3d-140c-4621-8c11-55d4bdf7c8d3.png)

**Comment by yochaigal** [comment]
Wow, I had never even _considered_ this!

**Comment by lars1808** [comment]
Yeah, Monk's Enhanced Journal can read out a value but needs a "code". I tried 'gold' and a couple of variations that I glanced from the console (I'm not a developer, but hey, I tried) and that didn't work. 
Labeling items with value would make it easy to sell loot, add items to store tables, add/subtract the player's gold values automatically... :)

**Comment by Drakynn** [comment]
Leaving aside 3rd party plugins, it would be nice to have "cost" as an attribute for the base item object and include that in the UI for all item types.

Playing Cairn using Foundry should minimize the amount of times players and wardens need to reference the game manual.  Look-ups in the compendium would be preferable.

Now, once "cost" is defined, that opens up a whole world of plugins or home-brew macros for automation within the game.  Personally I like writing macros as it reduces 3rd party dependency.

**Comment by oswida** [comment]
I think the idea of an item cost looks nice.
