### ISSUE TITLE
Changing the number of uses for a weightless item changes its quantity

### ISSUE THREAD

**Issue by jdy687** [yochaigal/Cairn-FoundryVTT#82]
When clicking on the + or - buttons next to a weightless inventory item with a number of uses, the quantity of the item goes up or down rather than the number of uses left.

**Comment by oswida** [comment]
This is working almost as planned - weightless item means that you can have as many of it as you want, in the single equipment slot. Thus plus/minus is changing quantity instead of number of uses. However, we should hide use counter for weightless items.
