### ISSUE TITLE
Generate character macro - doesn't add items to charsheet

### ISSUE THREAD

**Issue by ScottMaclure** [yochaigal/Cairn-FoundryVTT#9]
Apologies again, am new to FoundryVTT/Cairn system code, but it seems like the random items rolled during chargen macro are not added to the charsheet?

![image](https://user-images.githubusercontent.com/962320/114258176-565f7380-99f7-11eb-82fb-c187a69e1a34.png)

Would be nice if when you use that generate character macro, all the items are added to the Actor.

**Comment by yochaigal** [comment]
Correct, this is a much bigger problem we haven't fixed yet. For now you can drag+drop items into the sheet. It's def the #1 requested feature though.

**Comment by yochaigal** [comment]
Fixed!
