### ISSUE TITLE
[Bug] Dragging an item from an actor back to itself can delete other items (Fix included)

### ISSUE THREAD

**Issue by HeroicCookie** [yochaigal/Cairn-FoundryVTT#93]
If you have two items in a character sheet and drag one on top of the other, it deletes the item you dragged on top of.

In the actor-sheet.js, change the _onDropItem function to include the following line after getting the item data:

`if (this.actor == originalActor) return;`

**Comment by yochaigal** [comment]
I'm not maintaining this anymore. Feel free to fork, though.

**Comment by oswida** [comment]
Fixed.
